# @format

name: 📖 User Story
description: Пользовательская история в формате роли, цели и ценности
title: "[STORY]:"
labels: ["story"]
assignees: []

body:
    - type: input
      id: role
      attributes:
          label: 👤 Роль
          description: Кто является инициатором запроса
          placeholder: |
              Например: Менеджер / Клиент / Сотрудник склада
      validations:
          required: true

    - type: input
      id: goal
      attributes:
          label: 🎯 Цель
          description: Что пользователь хочет сделать
          placeholder: |
              Например: видеть статус отправки заказа
      validations:
          required: true

    - type: textarea
      id: userStory
      attributes:
          label: 📝 Сценарий (автоматически или вручную)
          description: |
              Автосборка: “Как [роль], я хочу [цель], чтобы [ценность]” или напиши вручную
          placeholder: |
              Например: Как менеджер, я хочу видеть статус отправки заказа, чтобы своевременно уведомить клиента.
      validations:
          required: false

    - type: textarea
      id: acceptance
      attributes:
          label: ✅ Acceptance Criteria
          description: Что должно быть выполнено, чтобы задача считалась завершённой
          placeholder: |
              - [ ] Пользователь может ...
              - [ ] После действия происходит ...
      validations:
          required: true

    - type: input
      id: epic
      attributes:
          label: 🧱 Связанный Epic (если есть)
          placeholder: "#123"
      validations:
          required: false
