# @format

name: 📌 Задача (Backend / Frontend)
description: Создание задачи для проекта (backend, frontend)
title: "[TASK]:"
labels: ["task"]
assignees: []

body:
    - type: textarea
      id: table
      attributes:
          label: 📋 Табличное описание задачи
          description: Заполни таблицу в формате Markdown. Используй шаблоны ниже в зависимости от типа задачи.
          value: |
              ### Backend

              | Field   | Description |
              |--------|-------------|
              | Route    | `api/...` |
              | Method   | GET/POST/PUT/DELETE |
              | Body     | `param1, param2` |
              | Action 1 | ... |
              | Response | ... |
              | Exception | ... |
              | Comments  | ... |

              ### Frontend

              | Field        | Description |
              |-------------|-------------|
              | Path         | `/path/to/component` |
              | Name         | Название компонента |
              | Action       | Что нужно сделать |
              | Requirements | Требования |
              | Exception    | Ошибки и особые случаи |
              | Response     | Что должно произойти |
              | Comment      | Комментарии |
              | Design       | [Ссылка на Figma] |

      validations:
          required: true

    - type: textarea
      id: additional
      attributes:
          label: 🧩 Дополнительная информация
          description: Любая другая информация, которая может помочь разработчику
          placeholder: Необязательное поле
      validations:
          required: false
